### ISSUE TITLE
Error Get App ID

### ISSUE THREAD

**Issue by ipBill** [cianru/huawei-publish-gradle-plugin#11]
<img width="975" alt="Screen Shot 2563-11-06 at 12 33 26" src="https://user-images.githubusercontent.com/8220639/98330244-8d86be80-202c-11eb-8aa0-03994b8d28e9.png">

**Comment by cosic** [comment]
@ipBill Hi! What version of Android Gradle Plugin are you using? Could you get me a little bit more information about you  environment?

**Comment by mdenissov** [comment]
@ipBill Looks, like you uses wrong client_id & client_secret. Verify, that you create API Access via https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-Guides/agcapi-getstarted

Plugin returns null as token value and getAppID doesn't work when uses wrong client_id & client_secret.

Be attention! DO NOT SET UP a project in the project field, use N/A, otherwise you will get `403 client token authorization fail.` error.

**Comment by ipBill** [comment]
Thank you for your suggestion.  It's my fault. I'm so sorry.

**Comment by mPetrus** [comment]
@mdenissov Hi, I have the same issue - `403 client token authorization fail` but I do not know what do you mean by `DO NOT SET UP a project in the project field, use N/A`. 
What do you mean by project field?
@ipBill How did you fixed your issue?
Thanks
